version: "3"
services:
  nginx:
    image: nginx:1.14.0-alpine
    ports:
      - 80:80
    environment:
      TZ: "Asia/Shanghai"
    # restart: always
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../config/nginx/conf.d:/etc/nginx/conf.d
      - ../log/nginx:/var/log/nginx
      
  flaskapp:
    image: flaskapp
    build: ./flaskapp
    volumes:
      - ../src:/usr/app/src
    working_dir: /usr/app/src
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: "development"
      FLASK_APP: /usr/app/src/hello.py
    ports:
      - 9001:9001
    command: gunicorn -w 4 -b 127.0.0.1:9001 hello:app
    # command: flask run --host=0.0.0.0